services:
  - type: web
    name: canvas-backend
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false

staticSites:
 - type: web
    name: canvas-frontend
    env: static
    rootDir: .
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true
